"use client"

import { PermissionGuard } from "@/components/auth/permission-guard"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { SidebarTrigger } from "@/components/ui/sidebar"
import { Download, FileText, Calendar, TrendingUp, Users, Activity } from "lucide-react"

interface Report {
  id: string
  name: string
  type: string
  generatedBy: string
  date: string
  size: string
  status: "Ready" | "Generating" | "Failed"
}

const mockReports: Report[] = [
  {
    id: "1",
    name: "Monthly Patient Report",
    type: "Patient Analytics",
    generatedBy: "Dr. Admin",
    date: "2024-01-15",
    size: "2.4 MB",
    status: "Ready",
  },
  {
    id: "2",
    name: "Lab Results Summary",
    type: "Laboratory",
    generatedBy: "Lab Tech Mike",
    date: "2024-01-14",
    size: "1.8 MB",
    status: "Ready",
  },
  {
    id: "3",
    name: "Financial Report Q1",
    type: "Financial",
    generatedBy: "Sarah Johnson",
    date: "2024-01-13",
    size: "3.2 MB",
    status: "Generating",
  },
  {
    id: "4",
    name: "Appointment Statistics",
    type: "Scheduling",
    generatedBy: "Dr. Smith",
    date: "2024-01-12",
    size: "1.1 MB",
    status: "Ready",
  },
]

export default function ReportsPage() {
  const getStatusColor = (status: string) => {
    switch (status) {
      case "Ready":
        return "default"
      case "Generating":
        return "secondary"
      case "Failed":
        return "destructive"
      default:
        return "secondary"
    }
  }

  const reportTypes = [
    { name: "Patient Analytics", count: 12, icon: Users },
    { name: "Laboratory", count: 8, icon: Activity },
    { name: "Financial", count: 6, icon: TrendingUp },
    { name: "Scheduling", count: 4, icon: Calendar },
  ]

  return (
    <PermissionGuard permissions={["canExportReports", "canViewAllPatients"]}>
      <div className="flex flex-1 flex-col gap-4 p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <SidebarTrigger />
            <div>
              <h1 className="text-2xl font-bold">Reports</h1>
              <p className="text-muted-foreground">Generate and manage system reports</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Select>
              <SelectTrigger className="w-48">
                <SelectValue placeholder="Select report type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="patient">Patient Analytics</SelectItem>
                <SelectItem value="lab">Laboratory Reports</SelectItem>
                <SelectItem value="financial">Financial Reports</SelectItem>
                <SelectItem value="scheduling">Scheduling Reports</SelectItem>
              </SelectContent>
            </Select>
            <Button>
              <FileText className="h-4 w-4 mr-2" />
              Generate Report
            </Button>
          </div>
        </div>

        <div className="grid gap-4 md:grid-cols-4">
          {reportTypes.map((type) => (
            <Card key={type.name}>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">{type.name}</CardTitle>
                <type.icon className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{type.count}</div>
                <p className="text-xs text-muted-foreground">reports available</p>
              </CardContent>
            </Card>
          ))}
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Recent Reports</CardTitle>
            <CardDescription>Generated reports and their current status</CardDescription>
          </CardHeader>

          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report Name</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Size</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {mockReports.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell className="font-medium">{report.name}</TableCell>
                    <TableCell>{report.type}</TableCell>
                    <TableCell>{report.generatedBy}</TableCell>
                    <TableCell>{report.date}</TableCell>
                    <TableCell>{report.size}</TableCell>
                    <TableCell>
                      <Badge variant={getStatusColor(report.status) as any}>{report.status}</Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        {report.status === "Ready" && (
                          <Button variant="ghost" size="sm">
                            <Download className="h-4 w-4 mr-1" />
                            Download
                          </Button>
                        )}
                        <Button variant="ghost" size="sm">
                          View
                        </Button>
                        <Button variant="ghost" size="sm">
                          Share
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Quick Reports</CardTitle>
              <CardDescription>Generate common reports instantly</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-2">
                <Button variant="outline" className="justify-start bg-transparent">
                  <Users className="h-4 w-4 mr-2" />
                  Daily Patient Summary
                </Button>
                <Button variant="outline" className="justify-start bg-transparent">
                  <Activity className="h-4 w-4 mr-2" />
                  Lab Results Today
                </Button>
                <Button variant="outline" className="justify-start bg-transparent">
                  <Calendar className="h-4 w-4 mr-2" />
                  Appointment Schedule
                </Button>
                <Button variant="outline" className="justify-start bg-transparent">
                  <TrendingUp className="h-4 w-4 mr-2" />
                  Revenue Summary
                </Button>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Report Templates</CardTitle>
              <CardDescription>Saved report configurations</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                <div className="flex items-center justify-between p-2 border rounded">
                  <span className="text-sm">Monthly Overview</span>
                  <Button variant="ghost" size="sm">
                    Use
                  </Button>
                </div>
                <div className="flex items-center justify-between p-2 border rounded">
                  <span className="text-sm">Weekly Lab Summary</span>
                  <Button variant="ghost" size="sm">
                    Use
                  </Button>
                </div>
                <div className="flex items-center justify-between p-2 border rounded">
                  <span className="text-sm">Patient Demographics</span>
                  <Button variant="ghost" size="sm">
                    Use
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </PermissionGuard>
  )
}
